.dockerignore, .gitattributes, Dockerfile, Makefile, docker-compose.yml
On branch addDockerAgain
Changes to be committed:
new file:   .dockerignore
new file:   .gitattributes
new file:   Dockerfile
new file:   Makefile
new file:   docker-compose.yml
[Goes here]
=> Added standard Docker build from InformedCD

app/routes.js, app/views/index.html, app/views/vehicle-checker-2/birmingham/index.html, app/views/vehicle-checker-2/compliance/index.html, app/views/vehicle-checker-2/confirm/index.html, app/views/vehicle-checker-2/enter-vehicle-details/index.html, app/views/vehicle-checker-2/index.html, app/views/vehicle-checker-2/leeds/index.html, app/views/vehicle-checker-2/local-authority/index.html
Alternative prototype to enter the VRM details before selecting the CAZ LA.
=> Enter VRM details before selecting CAZ LA

app/views/vehicle-checker/variant/dropdown.html
=> small fixes

app/views/includes/birmingham.html, app/views/includes/derby.html, app/views/includes/leeds.html, app/views/includes/nottingham.html, app/views/includes/southampton.html, app/views/index.html, app/views/vehicle-checker/confirm/index.html, app/views/vehicle-checker/enter-vehicle-details/index.html, app/views/vehicle-checker/local-authority/index.html
=> Content changes

app/views/vehicle-checker/compliancePage.html, app/views/vehicle-checker/not-recognised/index.html
=> Further content changes

app/views/includes/birmingham.html, app/views/includes/compliant.html, app/views/includes/derby.html, app/views/includes/leeds.html, app/views/includes/notCompliant.html, app/views/includes/nottingham.html, app/views/includes/southampton.html, app/views/vehicle-checker/compliancePage.html, app/views/vehicle-checker/confirm/index.html, app/views/vehicle-checker/incorrect-details/index.html
Prototype changes for Sprint 6
=> Prototype changes for Sprint 6

app/views/index.html, app/views/vehicle-checker/birmingham/1.html, app/views/vehicle-checker/birmingham/2.html, app/views/vehicle-checker/birmingham/3.html, app/views/vehicle-checker/birmingham/index.html, app/views/vehicle-checker/birmingham/singular.html, app/views/vehicle-checker/birmingham/withCharge.html, app/views/vehicle-checker/compliancePage.html, app/views/vehicle-checker/leeds/index.html, app/views/vehicle-checker/local-authority/index.html, app/views/vehicle-checker/summary.html, app/views/vehicle-checker/variant/compliant.html, app/views/vehicle-checker/variant/dropdown.html, app/views/vehicle-checker/variant/may-be-charged.html, app/views/vehicle-checker/variant/subject-to-charge.html, app/views/vehicle-checker/variant/summary.html
Remove Local Authorities not implementing a charging Clean Air Zone.
=> Remove LAs not implementing a charging CAZ

app/views/index.html, app/views/vehicle-checker/confirm/index.html, app/views/vehicle-checker/incorrect-details/index.html
=> Minor content changes

app/views/payments/bath.html
Sample JavaScript code to update a value on the page.
=> Add JavaScript function to change tariff

app/views/includes/bath.html, app/views/index.html, app/views/vehicle-checker/local-authority/index.html
Refine content on Local Authority selection page
=> Refine content on Local Authority selection page

app/views/index.html, app/views/layout.html, app/views/vehicle-checker/compliancePage.html, app/views/vehicle-checker/confirm/index.html, app/views/vehicle-checker/incorrect-details/index.html
Content refinements following a review from the content designer.
=> Content refinements

app/views/layout.html
=> Remove navigation tabs

.gitignore, app/config.js, app/views/payments/bath.html, app/views/payments/debit-credit-card.html, app/views/payments/index.html, app/views/payments/local-authority.html
Content refinements and payment summary box
=> Content refinements and payment summary box

app/routes.js, app/views/layout.html, app/views/payments/bath.html, app/views/payments/debit-credit-card.html, app/views/payments/pay-money.html
Add more payment summary boxes
=> Add more payment summary boxes

app/routes.js, app/views/payments/bath.html, app/views/payments/birmingham.html, app/views/payments/confirm-payment.html, app/views/payments/debit-credit-card.html, app/views/payments/leeds.html, app/views/payments/local-authority.html, app/views/payments/no-payment.html, app/views/payments/pay-money.html, app/views/payments/sheffield.html
Content refinements and passing data through to payment confirmation page
=> Content refinements and passing data through to payment confirmation page

app/views/payments/confirm-payment.html
Content refinements to confirmation page
=> Content refinements to confirmation page

app/views/includes/bath.html, app/views/includes/leeds.html, app/views/vehicle-checker/local-authority/index.html
Update LA links following LA site changes
=> Update LA links

app/routes.js, app/views/payments/bath.html, app/views/payments/local-authority.html
Add temporary payment suspension example
=> Add temporary payment suspension example

app/routes.js, app/views/payments/local-authority.html, app/views/payments/sheffield.html
=> Refine Sheffield page

app/views/payments/account-details.html, app/views/payments/account-home.html, app/views/payments/account-payments.html, app/views/payments/account-vehicles.html
Content refinements to accounts pages
=> Content refinements to accounts pages

app/views/payments/account-details.html, app/views/payments/account-home.html, app/views/payments/account-payment-options.html, app/views/payments/account-payments.html, app/views/payments/account-vehicles.html, app/views/payments/index.html, app/views/payments/sign-in.html
=> Add Discovery requirements

app/views/payments/account-payments.html
=> Refine payment history page

app/views/includes/phase-banner.html, app/views/layout.html, app/views/payments/local-authority.html
=> Update links and phase banner

app/views/payments/sheffield.html
Remove discounts for Sheffield
=> Remove discounts for Sheffield

app/views/payments/index.html
Update Assisted Digital payment methods on start page.
=> Update Assisted Digital payment methods

app/views/payments/debit-credit-card.html, app/views/payments/pay-money.html
Add digital wallets and update Enter card details page
=> Add digital wallets and update Enter card details page

app/views/includes/bath.html, app/views/includes/birmingham.html, app/views/index.html, app/views/vehicle-checker/compliancePage.html, app/views/vehicle-checker/confirm/index.html, app/views/vehicle-checker/enter-vehicle-details/index.html, app/views/vehicle-checker/local-authority/index.html
Behavioural change messaging and content refinements
=> Behavioural change messaging and content refinements

app/views/includes/bath.html, app/views/includes/birmingham.html, app/views/includes/leeds.html, app/views/includes/sheffield.html, app/views/vehicle-checker/compliancePage.html
Content refinements to compliance page
=> Content refinements to compliance page

.github/PULL_REQUEST_TEMPLATE.md
=> [NON-JIRA] Update PR template

.githooks/pre-commit, .github/workflows/Informed.Repo.CredentialScan.Verified.CI.yml, Makefile, SECURITY.md, credential-scan-exclusions.txt
=> [CAZB-8128] GitHub credential scan

.github/workflows/Informed.Repo.CredentialScan.Verified.CI.yml
=> [CAZB-10511] - updating trufflehog with pull requests
